CREATE TABLE sales (
    sale_id NUMBER,
    sale_date DATE,
    amount NUMBER
)
PARTITION BY RANGE (sale_date) (
    PARTITION p2025 VALUES LESS THAN (TO_DATE('01-JAN-2026','DD-MON-YYYY')),
    PARTITION p2026 VALUES LESS THAN (TO_DATE('01-JAN-2027','DD-MON-YYYY'))
);
