CREATE MATERIALIZED VIEW sales_summary
REFRESH ON DEMAND
AS
SELECT sale_date, SUM(amount) AS total_sales
FROM sales
GROUP BY sale_date;

EXEC DBMS_MVIEW.REFRESH('SALES_SUMMARY', 'C');

EXEC DBMS_MVIEW.REFRESH('SALES_SUMMARY', 'F');
