CREATE USER project_user IDENTIFIED BY projPass
DEFAULT TABLESPACE projects
QUOTA 50M ON projects;

CREATE USER project_user IDENTIFIED BY projPass
DEFAULT TABLESPACE projects
QUOTA UNLIMITED ON projects;
